# Generated by Django 3.2.4 on 2021-07-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('AdditionalInfo', models.TextField(max_length=500)),
                ('Product', models.CharField(max_length=300)),
                ('Amount', models.IntegerField()),
            ],
        ),
    ]
