# Generated by Django 3.2.4 on 2021-07-03 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheGenuinesWeb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderInfo',
        ),
    ]
