# Generated by Django 3.2.4 on 2021-07-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TheGenuinesWeb', '0002_delete_orderinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('AdditionalInfo', models.TextField()),
                ('Product', models.CharField(max_length=150)),
                ('Amount', models.IntegerField()),
                ('OrderDate', models.DateField()),
                ('OrderTime', models.TimeField()),
            ],
        ),
    ]
