# Generated by Django 3.2.4 on 2021-07-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheGenuinesWeb', '0003_myorderinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorderinfo',
            name='Name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='myorderinfo',
            name='Product',
            field=models.CharField(max_length=300),
        ),
    ]
